### ISSUE TITLE
Need Advanced Search component page

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#13] opened 2020-09-18 14:02 UTC
Currently, if you click on the "Search" item at the upper right, you get a basic search by name page

<img width="818" alt="Screen Shot 2020-09-18 at 8 54 32 AM" src="https://user-images.githubusercontent.com/14842313/93605899-f6d34500-f98c-11ea-9599-c1fb13a70566.png">

What we need is a new component for "Advanced Search"es.  Right now, it only needs to contain two options -- "Name", a free form text field, and "Enabled", which should be a menu of three options -- "None Selected," "True," or "False".  There shoudl also be a submit button.

Additionally, we need a menu item that reads "Advanced Search" as well as a link ("Advanced") just to the right of the "Search" text field in the screen shot above.

We don't need to wire it up to anything just yet (Mostly because backend isn't ready to go).

URL: The URL for submitting to the search page should look like

```
/coops/?name=coopName&type=credit+union&enabled=true&street=Main&city=Chicago&zip=60605&state=IL
```

as an example.  The parameters (all optional) are:

```
name
type
enabled
street
city
state
zip
```

**Comment by ozzysChiefDataScientist** [comment] 2021-03-15 01:53
Hi @laredotornado  - This is Elena. Can you assign this ticket to me? Thank you!

**Comment by ozzysChiefDataScientist** [comment] 2021-03-23 02:11
Thanks! Just a quick update -- I worked on the code this weekend and it's behaving as expected. Just want to add some more comments and review with fresh eyes before submitting. Planning to submit by 3/30.

**Comment by laredotornado** [comment] 2021-03-23 20:32
That's awesome!  So it's working ok when submitting to the backend? -

**Comment by ozzysChiefDataScientist** [comment] 2021-03-24 00:50
Hi Dave,
Good question. The image below shows some examples of what the advanced search form looks like when certain actions are performed.
<img width="691" alt="chi_commons_view_examples" src="https://user-images.githubusercontent.com/42755977/112237408-9c9f8f00-8c10-11eb-87eb-f8641c1fc597.png">

Is it OK that the search results shows all coops, even those that do not match the search terms? I assumed this was the expected behavior since the ticket says that the backend isn't ready to go.

If the search results don't look right to you, I'll need to edit the code. My code builds out a URL to submit for search based on values entered in the form. In the example above, the search URL is `/coops/?name=1871&enabled=true`.

**Comment by laredotornado** [comment] 2021-03-24 21:40
Ah you are right on that one -- I still need to make a few more tweaks to
get the backend up and running.  But looking good so far on your end!

**Closed** 2021-04-04 16:48 UTC

**Comment by laredotornado** [comment] 2021-04-09 15:48
Adding a note to track the last issue related to this ticket, which is when
the Enabled menu is defaulted to an item (e.g. "True"), clicking "Submit"
does not appear to submit the search params properly.  Switching the menu
to another option (e.g. "False") and then back to "True", followed by
clicking submit sends and returns the proper search results.

**Comment by ozzysChiefDataScientist** [comment] 2021-04-19 23:20
Hi Dave,

Thanks. I understand now why search results don't show initially, if a user
presses 'Submit' without changing any settings. I developed a solution to
fix it, but it feels a little hack-y to me. I'm really busy this week, but
hoping I can spend some time next weekend coming up with a more elegant
solution.

Thanks,
Elena
