### ISSUE TITLE
BACKEND: Endpoint "password-reset-confirm" missing request body

### ISSUE THREAD

**Issue by akist529** [chicommons/maps#253] opened 2024-06-05 01:31 UTC
The documentation for the following POST endpoint: 

/api/v1/password-reset-confirm/{uidb64}/{token}/

Does not state a required request body. This needs to be updated as the new password needs to be included in the request body as a string value.

**Comment by maxgraziano** [comment] 2024-08-15 18:42
Duplicate of #245

**Closed as completed by maxgraziano** 2024-08-15 18:42 UTC
